#define LED_R 26
#define LED_G 27
#define LED_B 14
#define BUZZER 33

#define START_BUTTON 25 

#define PLAYER1_BUTTON_R 23
#define PLAYER1_BUTTON_G 5 
#define PLAYER1_BUTTON_B 18

#define PLAYER2_BUTTON_R 19
#define PLAYER2_BUTTON_G 12
#define PLAYER2_BUTTON_B 15

#define POTENTIOMETER 32
#define STRIP_WS2812B 2
#define STRIP_COUNT 6

#define OLED_DISPLAY_SDA 21
#define OLED_DISPLAY_SCL 22
#define OLED_ADDR 0x3C
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define SERVO_PAS_LE_TRUC_KON_A_DAN_LE_TETE 18